#!/usr/bin/env python
"""Build docs/COVERAGE_MATRIX.md from executed evidence.

Inputs
------
docs/coverage/ml_topics.yaml    the FROZEN topic inventory (42 topics) with
                                traceability to every file of the Data
                                Science and machine learning folder
docs/coverage/evidence.yaml     for each claimed topic: project purpose,
                                implementation (file + symbol), evidence
                                (keys in summary.json and/or files) and what
                                was learned
results/<cfg>/metrics/summary.json   produced by scripts/run_pipeline.py

A topic is counted as COVERED only if
  * it is in the frozen inventory (hash checked),
  * every implementation symbol is found in the named source file,
  * every evidence key exists in summary.json and is not marked
    failed/skipped/unavailable, and every evidence file exists,
  * a purpose and a 'learned' statement are given.
Anything else is reported as NOT COVERED with the reason.

    python scripts/build_coverage.py --config config/demo.yaml
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


def _get(d, path):
    for k in path.split("."):
        if isinstance(d, dict) and k in d:
            d = d[k]
        else:
            return None
    return d


def _bad(v):
    if v is None:
        return "missing"
    if isinstance(v, dict):
        st = str(v.get("status", "")).lower()
        if v.get("skipped") or st.startswith(("failed", "unavailable", "skipped")):
            return f"status={st or 'skipped'}"
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(ROOT / "config" / "demo.yaml"))
    a = ap.parse_args()
    from subsurfaceml.config import load_config
    cfg = load_config(a.config)
    topics = yaml.safe_load((ROOT / "docs/coverage/ml_topics.yaml").read_text())
    frozen = (ROOT / "docs/coverage/FROZEN_TOPICS.sha256").read_text().split()[0]
    h = hashlib.sha256(json.dumps({k: v["name"] for k, v in topics["topics"].items()},
                                  sort_keys=True).encode()).hexdigest()
    if h != frozen:
        print("ERROR: the topic inventory changed after it was frozen "
              f"({h[:12]} != {frozen[:12]}). Refusing to compute coverage.")
        return 2
    ev = yaml.safe_load((ROOT / "docs/coverage/evidence.yaml").read_text()) or {}
    summ_p = Path(cfg.paths.metrics) / "summary.json"
    if not summ_p.exists():
        print(f"ERROR: {summ_p} not found - run the pipeline first")
        return 2
    summ = json.loads(summ_p.read_text())
    rows, n_cov = [], 0
    for tid, t in topics["topics"].items():
        e = ev.get(tid)
        reasons = []
        if not e:
            reasons.append(e is None and "no implementation claimed" or "empty")
            status = "NOT COVERED"
        else:
            if e.get("status") == "not_covered":
                reasons.append(e.get("reason", "not implemented"))
            for imp in e.get("implementation", []):
                f, sym = imp.split("::")
                src = (ROOT / f)
                if not src.exists() or sym not in src.read_text():
                    reasons.append(f"symbol {sym} not found in {f}")
            for k in e.get("evidence_keys", []):
                b = _bad(_get(summ, k))
                if b:
                    reasons.append(f"evidence {k}: {b}")
            for f in e.get("evidence_files", []):
                p = Path(cfg.paths.results) / f
                if not p.exists():
                    reasons.append(f"evidence file {f} missing")
            if e.get("status") != "not_covered" and not (e.get("purpose") and e.get("learned")):
                reasons.append("purpose/learned statement missing")
            status = "COVERED" if not reasons else "NOT COVERED"
        n_cov += status == "COVERED"
        rows.append((tid, t, e or {}, status, reasons))
    n = len(topics["topics"])
    pct = 100.0 * n_cov / n
    L = ["# ML topic coverage matrix", "",
         f"Generated by `scripts/build_coverage.py --config {Path(a.config).as_posix()}` "
         f"from `{summ_p.relative_to(ROOT).as_posix() if summ_p.is_relative_to(ROOT) else summ_p}`.", "",
         f"**Coverage = {n_cov} / {n} = {pct:.1f}%** of the unique substantive topics "
         "in the supplied *Data Science and machine learning* folder "
         "(denominator frozen before methods were selected; see "
         "`docs/coverage/ml_topics.yaml` for the inventory, granularity rule, "
         "exclusions and the file-by-file traceability including duplicates).", "",
         "A topic counts only when it has a source, a project purpose, working code, "
         "executed evidence in this run and a stated finding. The checks are automatic "
         "(symbol present in the source file, evidence present and not failed).", "",
         "| ID | Topic | Course source(s) | Project purpose | Implementation | Executed evidence | Status | What was learned |",
         "|---|---|---|---|---|---|---|---|"]
    for tid, t, e, status, reasons in rows:
        src = "; ".join(f"`{s}`" for s in t["sources"][:3]) + (" …" if len(t["sources"]) > 3 else "")
        imp = "<br>".join(f"`{x}`" for x in e.get("implementation", [])) or "—"
        evk = "<br>".join([f"`{k}`" for k in e.get("evidence_keys", [])] +
                          [f"`{f}`" for f in e.get("evidence_files", [])]) or "—"
        learned = e.get("learned", "") if status == "COVERED" else \
            ("; ".join(reasons))
        L.append(f"| {tid} | {t['name']} | {src} | {e.get('purpose', '—')} | {imp} | {evk} | "
                 f"**{status}** | {learned} |")
    L += ["", "## Excluded material (not counted in the denominator)", ""]
    for x in topics["excluded"]:
        L.append(f"* {x['what']} — {', '.join(f'`{f}`' for f in x['files'])}: {x['reason']}")
    out = ROOT / "docs" / "COVERAGE_MATRIX.md"
    out.write_text("\n".join(L) + "\n")
    (Path(cfg.paths.metrics) / "coverage.json").write_text(json.dumps(
        {"covered": n_cov, "total": n, "percent": pct,
         "not_covered": {tid: r for tid, _, _, s, r in rows if s != "COVERED"}}, indent=2))
    print(f"coverage {n_cov}/{n} = {pct:.1f}%  -> {out}")
    for tid, _, _, s, r in rows:
        if s != "COVERED":
            print(f"  {tid}: {'; '.join(r)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
