#!/usr/bin/env python
"""(Re)write the notebooks from this script so their code stays in one
reviewed place.  Execute them afterwards with

    python scripts/make_notebooks.py --execute

There is one entry point, ``notebooks/00_START_HERE.ipynb`` (the walkthrough),
and five optional supporting notebooks in ``notebooks/supporting/``.  The
notebooks call the package code only; they re-implement nothing.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks"
SUP = NB / "supporting"

# One setup cell for every notebook.  ``CONFIG`` selects which completed run the
# notebook reads: 'study' is the large run quoted in the report, 'demo' the small
# one anybody can reproduce in ten minutes.
HEADER = """import sys, json, time
from pathlib import Path
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'pyproject.toml').exists())
sys.path.insert(0, str(ROOT / 'src'))
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from IPython.display import Image, display
from subsurfaceml.config import load_config

CONFIG = '{config}'                 # which completed run this notebook reads
cfg = load_config(ROOT / 'config' / f'{{CONFIG}}.yaml')
S = json.loads((Path(cfg.paths.metrics) / 'summary.json').read_text())
pd.set_option('display.max_colwidth', 80)
plt.rcParams.update({{'figure.dpi': 110, 'axes.grid': True, 'grid.alpha': .3,
                     'font.size': 9, 'figure.constrained_layout.use': True}})


def provenance(kind, what):
    \"\"\"Label every result: read from a finished run, or computed right here.\"\"\"
    label = {{'loaded': 'LOADED from the completed ' + CONFIG + ' run',
             'computed': 'COMPUTED NOW in this notebook session'}}[kind]
    print(f'[{{label}}]  {{what}}')"""

SETUP = HEADER.format(config="demo")
SETUP_STUDY = HEADER.format(config="study")


def md(s):
    return nbf.v4.new_markdown_cell(s)


def code(s):
    return nbf.v4.new_code_cell(s)


def nb00():
    """The one notebook a reader should open first."""
    return [
        md("# CO2 storage in a layered saline aquifer: simulator, surrogates, limits\n\n"
           "**The question.** How do permeability, heterogeneity, fluid mobility and the "
           "injection schedule control the pressure build-up at the well and the spread "
           "of the CO2 plume in a sealed, layered saline aquifer -- and can a cheap "
           "machine-learning surrogate, trained on simulations, answer that for a "
           "reservoir it has never seen?\n\n"
           "**What this notebook is.** The walkthrough of the whole project, in order, "
           "end to end. It runs a simulation, then reads the results of a finished run "
           "and re-checks the headline numbers. Every output is labelled either\n\n"
           "* `[LOADED from the completed study run]` -- read from `results/study/`, "
           "produced by `scripts/run_pipeline.py` on 2026-09-20, or\n"
           "* `[COMPUTED NOW in this notebook session]` -- calculated while you run "
           "these cells.\n\n"
           "**Plan**\n\n"
           "1. Purpose, scope and assumptions\n"
           "2. Simulation: one injection case, run here\n"
           "3. Verification: does the simulator solve the right equations?\n"
           "4. Dataset and the grouped split\n"
           "5. Surrogate training\n"
           "6. Held-out evaluation, re-checked here\n"
           "7. Screening injection schedules, including where it fails\n"
           "8. Conclusions and limitations\n\n"
           "**Everything here comes from two sets of supplied course material**: the "
           "*Advanced Subsurface Modelling* lectures (transmissibility, upscaling, "
           "IMPES, CO2 Buckley-Leverett, uncertainty) and the *Data Science and Machine "
           "Learning* notebooks. No method, dataset or library outside that material is "
           "used; `docs/SOURCE_MAP.md` names the file behind each component.\n\n"
           "**All data are synthetic**, generated by the simulator in this repository. "
           "Nothing is calibrated to, or validated against, a real site."),
        code(SETUP_STUDY + "\n\n"
             "provenance('loaded', f\"run of {S['config_file']} started {S['started']}, \"\n"
             "           f\"{S['total_wall_seconds']/60:.1f} min wall, python \"\n"
             "           f\"{S['environment']['python']}, scikit-learn {S['environment']['scikit_learn']}\")"),

        md("## 1. Purpose, scope and assumptions\n\n"
           "The model is deliberately small, so that every part can be explained and "
           "checked. One rate-controlled injector sits at the centre of a sealed, "
           "cylindrical compartment split into horizontal layers. Each layer has its own "
           "permeability and porosity; there is **no vertical crossflow**, and all layers "
           "share **one bottom-hole pressure**, solved together with the pressure field.\n\n"
           "What is deliberately left out, and why:\n\n"
           "| Left out | Consequence |\n"
           "|---|---|\n"
           "| Gravity / buoyancy | the largest omission: no gravity override, so plume rise is not modelled |\n"
           "| Dissolution and residual trapping | storage security cannot be assessed |\n"
           "| Capillary pressure (`P_c = 0`) | the supplied material gives no CO2-brine curve (`4-CO2 BL.pdf` p.19) |\n"
           "| Vertical crossflow between layers | layer rates communicate only through the well |\n"
           "| Non-radial geometry, faults, wells beyond one | not a field model |\n\n"
           "The pressure and plume limits below are **stated assumptions** used to define "
           "a screening question. They say nothing about fracture pressure, caprock "
           "integrity or leakage, none of which is modelled. Full list: "
           "`docs/ASSUMPTIONS.md`."),
        code("c = S['config']\n"
             "print('reservoirs sampled      :', c['scenarios']['n_realisations'])\n"
             "print('schedules per reservoir :', c['scenarios']['n_schedules_per_realisation'])\n"
             "print('radial cells / layers   :', c['grid']['n_r'], '/', c['grid']['n_layers'])\n"
             "print('injection / total [yr]  :', c['schedule']['t_inject_years'], '/',\n"
             "      c['schedule']['t_total_years'], 'in', c['schedule']['n_periods'], 'rate periods')\n"
             "print('initial pressure  [MPa] :', c['solver']['p_init_MPa'])\n"
             "print('assumed limits          :', cfg.optim.p_limit_MPa, 'MPa at the well,',\n"
             "      cfg.optim.r_plume_limit_m, 'm plume radius')\n"
             "provenance('loaded', 'configuration of the completed run')"),

        md("## 2. Simulation: one injection case, run here\n\n"
           "The solver is IMPES (implicit pressure, explicit saturation) on a radial grid, "
           "with upstream mobilities and harmonic face transmissibilities, following "
           "`3-IMPES.pdf` and `1-Transmissibility.pdf`. The cell below takes the first "
           "held-out reservoir of the finished run, builds its designed schedule and "
           "simulates it from scratch, so you can see the two quantities the surrogates "
           "later predict: the pressure build-up at the well and the plume radius."),
        code("from subsurfaceml.scenarios import sample_realisations, sample_schedules, run_scenario\n"
             "from subsurfaceml.units import MPA, YEAR\n"
             "\n"
             "test_ids = S['ml']['split']['test_ids']\n"
             "reservoirs = {x.realisation_id: x for x in sample_realisations(cfg)}\n"
             "r = reservoirs[test_ids[0]]                  # a reservoir the models never saw\n"
             "sched = sample_schedules(cfg, r)[0]          # its first designed schedule\n"
             "print('reservoir', r.realisation_id, ': k =', round(r.k_median_mD), 'mD,',\n"
             "      'V_DP =', round(r.V_DP, 2), ', porosity =', round(r.phi_mean, 3),\n"
             "      ', thickness =', round(r.h_total_m), 'm')\n"
             "print('injection rates [kg/s]:', np.round(sched['rates_kg_s'], 2))\n"
             "\n"
             "t0 = time.perf_counter()\n"
             "out = run_scenario(cfg, r, sched, want_series=True)\n"
             "row, series = out['row'], out['series']\n"
             "provenance('computed', f\"one simulation in {time.perf_counter()-t0:.1f} s \"\n"
             "           f\"(CO2 mass-balance error {row['mass_balance_error']:.1e})\")\n"
             "print('peak pressure build-up    :', round(row['dp_bh_max_Pa']/MPA, 2), 'MPa')\n"
             "print('plume radius (95% of mass):', round(row['r_plume_m95_m']), 'm')"),
        code("fig, ax = plt.subplots(1, 2, figsize=(9.5, 3.1))\n"
             "ax[0].plot(series.t_s/YEAR, series.dp_bh_Pa/MPA, color='tab:blue')\n"
             "ax[0].axhline(cfg.optim.p_limit_MPa - cfg.solver.p_init_MPa, color='tab:red',\n"
             "              ls='--', lw=1, label='assumed limit')\n"
             "ax[0].set_xlabel('time [years]')\n"
             "ax[0].set_ylabel('pressure build-up at the well [MPa]')\n"
             "ax[0].set_title(f'Reservoir {r.realisation_id}: well pressure')\n"
             "ax[0].legend(fontsize=8)\n"
             "ax[1].plot(series.t_s/YEAR, series.r_plume_m95_m, color='tab:green')\n"
             "ax[1].set_xlabel('time [years]')\n"
             "ax[1].set_ylabel('plume radius, 95% of CO2 mass [m]')\n"
             "ax[1].set_title('CO2 plume extent')\n"
             "plt.show()\n"
             "provenance('computed', 'both curves come from the simulation above')"),

        md("## 3. Verification: does the simulator solve the right equations?\n\n"
           "Before any machine learning, the solver is checked against analytical and "
           "conservation results taken from the lectures: steady radial flow, the well "
           "equation, closed-tank material balance, the Buckley-Leverett/Welge front, CO2 "
           "mass balance, saturation bounds, grid and time-step convergence, upscaling "
           "bounds, and the common bottom-hole pressure across layers. The pipeline "
           "refuses to generate data if any check fails."),
        code("verdict = {k: v for k, v in S['validation_verdict'].items() if k != 'ALL_PASS'}\n"
             "V = pd.Series(verdict, name='pass').to_frame()\n"
             "print(f\"{int(V['pass'].sum())} of {len(V)} verification checks pass\")\n"
             "display(V.T)\n"
             "provenance('loaded', 'results/study/metrics/validation.json')"),

        md("## 4. Dataset and the grouped split\n\n"
           "Reservoir descriptions and injection schedules are drawn by Monte Carlo "
           "sampling (`5-Uncertainty.pdf`), and every combination is simulated. The unit "
           "of learning is the **reservoir realisation**, not the row: several schedules "
           "share one reservoir, so rows are not independent. All splits and all "
           "cross-validation folds are therefore grouped by `realisation_id` -- a "
           "reservoir is either in training, or in calibration, or in test, never in two."),
        code("df = pd.read_csv(Path(cfg.paths.data)/'scenarios_features.csv')\n"
             "print(len(df), 'simulated cases from', df.realisation_id.nunique(), 'reservoirs')\n"
             "print('rows per partition :', S['ml']['leakage']['rows'])\n"
             "print('reservoir overlaps :', S['ml']['leakage']['overlaps'], '(all must be 0)')\n"
             "print('failed simulations :', S['dataset']['n_failed'],\n"
             "      '| duplicate input rows:', S['data_quality']['duplicate_input_rows'],\n"
             "      '| missing values:', S['data_quality']['missing_values_total'])\n"
             "provenance('loaded', 'results/study/data/scenarios_features.csv')"),
        code("fig, ax = plt.subplots(1, 3, figsize=(11, 2.9))\n"
             "ax[0].hist(10**df.log10_k_mD, bins=30, color='tab:blue')\n"
             "ax[0].set_xscale('log'); ax[0].set_xlabel('median permeability [mD]')\n"
             "ax[0].set_ylabel('number of cases'); ax[0].set_title('Reservoir inputs')\n"
             "ax[1].hist(df.dp_bh_max_MPa, bins=30, color='tab:orange')\n"
             "ax[1].axvline(cfg.optim.p_limit_MPa - cfg.solver.p_init_MPa, color='tab:red', ls='--', lw=1)\n"
             "ax[1].set_xlabel('peak pressure build-up [MPa]'); ax[1].set_ylabel('number of cases')\n"
             "ax[1].set_title('Target 1 (red = assumed limit)')\n"
             "ax[2].hist(df.r_plume_m95_m, bins=30, color='tab:green')\n"
             "ax[2].set_xlabel('plume radius, 95% of mass [m]'); ax[2].set_ylabel('number of cases')\n"
             "ax[2].set_title('Target 2')\n"
             "plt.show()\n"
             "provenance('computed', 'histograms drawn from the loaded dataset')"),

        md("## 5. Surrogate training\n\n"
           "Eleven regression families from the *Data Science and Machine Learning* "
           "notebooks (linear, ridge, lasso, elastic net, k-nearest neighbours, SVR, "
           "decision tree, random forest, gradient boosting, AdaBoost, XGBoost), plus a "
           "mean-value baseline, are each placed in a scikit-learn pipeline (median "
           "imputation, standard scaling, model). Each is tuned by randomised search "
           "inside **grouped** 4-fold cross-validation on the training reservoirs only, "
           "and the family with the lowest cross-validated RMSE is selected and refitted "
           "on all training reservoirs. Pressure build-up and plume radius are fitted on "
           "a log scale; sweep efficiency is not. The calibration reservoirs are used "
           "only for the error band, and the saved models carry a SHA-256 manifest.\n\n"
           "Training is not repeated here -- these are the results of the finished run."),
        code("rows = []\n"
             "for t, res in S['ml']['targets'].items():\n"
             "    rows.append({'target': t, 'unit': res['unit'],\n"
             "                 'selected family': res['selected_model'],\n"
             "                 'log-scale fit': res['log_target'],\n"
             "                 'families compared': len(res['model_comparison_cv_rmse']),\n"
             "                 'grouped CV RMSE': round(res['cv_rmse_selected'], 4),\n"
             "                 'CV RMSE unit': res['cv_rmse_units']})\n"
             "display(pd.DataFrame(rows).set_index('target'))\n"
             "print('time to tune and fit every family [s]:',\n"
             "      round(S['speed']['surrogate_training_seconds']))\n"
             "provenance('loaded', 'model selection from results/study/metrics/summary.json')"),

        md("## 6. Held-out evaluation, re-checked here\n\n"
           "The test reservoirs were touched once, at the end. Errors are reported in "
           "physical units, against a mean-value baseline, together with the measured "
           "coverage of the empirical P5-P95 error band.\n\n"
           "The second cell does not trust the table: it loads the saved models, "
           "re-predicts the held-out rows and recomputes the metrics here. The two sets of "
           "numbers should agree to rounding."),
        code("rows = []\n"
             "for t, res in S['ml']['targets'].items():\n"
             "    rows.append({'target': t, 'unit': res['unit'], 'n test rows': res['test']['n'],\n"
             "                 'MAE': round(res['test']['MAE'], 4), 'RMSE': round(res['test']['RMSE'], 4),\n"
             "                 'R2': round(res['test']['R2'], 4),\n"
             "                 'worst case': round(res['test']['max_error'], 3),\n"
             "                 'baseline RMSE': round(res['mean_baseline_test']['RMSE'], 4),\n"
             "                 'band coverage': round(res['error_band']['measured_coverage_test'], 3)})\n"
             "display(pd.DataFrame(rows).set_index('target'))\n"
             "print('test reservoirs:', len(S['ml']['split']['test_ids']))\n"
             "provenance('loaded', 'held-out metrics of the completed study run')"),
        code("from subsurfaceml.predict import Predictor\n"
             "from subsurfaceml.features import FEATURES\n"
             "from subsurfaceml.models import regression_metrics\n"
             "\n"
             "P = Predictor(cfg)           # verified artifacts; refuses to load a mismatched version\n"
             "test = df[df.realisation_id.isin(P.manifest['test_realisation_ids'])]\n"
             "X = test[list(FEATURES)]\n"
             "check = []\n"
             "for t, model in P.surrogates.items():\n"
             "    m = regression_metrics(test[t], model.predict(X), S['ml']['targets'][t]['unit'])\n"
             "    check.append({'target': t, 'unit': m['unit'], 'n': m['n'],\n"
             "                  'RMSE recomputed': round(m['RMSE'], 4),\n"
             "                  'RMSE reported': round(S['ml']['targets'][t]['test']['RMSE'], 4),\n"
             "                  'R2 recomputed': round(m['R2'], 4),\n"
             "                  'R2 reported': round(S['ml']['targets'][t]['test']['R2'], 4)})\n"
             "display(pd.DataFrame(check).set_index('target'))\n"
             "provenance('computed', 'predictions and metrics recomputed from the saved models')"),
        code("display(Image(str(Path(cfg.paths.figures)/'06_surrogate_parity.png')))\n"
             "provenance('loaded', 'results/study/figures/06_surrogate_parity.png '\n"
             "           '(predicted vs simulated on held-out reservoirs, physical units)')"),
        md("Where the surrogates are weakest is as important as the average error. The "
           "worst tenth of the held-out cases carries a disproportionate share of the "
           "total error, and the low-permeability reservoirs are the hardest."),
        code("h = S['ml']['targets']['dp_bh_max_MPa']['difficult_cases']\n"
             "print('share of total absolute error from the worst 10% of cases:',\n"
             "      f\"{100*h['share_of_total_abs_error_from_worst_10pct']:.0f}%\")\n"
             "display(pd.DataFrame(h['by_permeability_tercile']))\n"
             "provenance('loaded', 'difficult-case analysis, pressure surrogate')"),

        md("## 7. Screening injection schedules, including where it fails\n\n"
           "The intended use of a fast surrogate: sample many candidate schedules for an "
           "unseen reservoir, keep those predicted to stay inside the assumed limits, then "
           "**re-simulate the shortlist and a constant-rate baseline**, because only the "
           "simulator decides. The result is mixed: on the reservoirs where a comparison "
           "was possible the median injected mass improves only slightly, and on one "
           "low-permeability reservoir every screened schedule -- and the constant-rate "
           "baseline -- broke the assumed pressure limit when re-simulated."),
        code("o = S['optimisation']\n"
             "print('reservoirs screened            :', o['n_test_realisations'])\n"
             "print('median improvement vs baseline :', round(o['median_improvement_pct'], 1), '%')\n"
             "print('screened schedules re-simulated:', o['n_screened_resimulated'])\n"
             "print('of those, violating the limit  :', o['n_screened_violating'],\n"
             "      f\"({100*o['screened_violation_rate']:.0f}%)\")\n"
             "per = pd.DataFrame(o['per_realisation']).round(3)\n"
             "display(per.set_index('realisation_id'))\n"
             "print('speed-up of a surrogate call over a simulation: '\n"
             "      f\"{S['speed']['speedup_batched']:.0f}x batched, \"\n"
             "      f\"{S['speed']['speedup_single_end_to_end']:.0f}x end to end \"\n"
             "      '(excludes data generation and training)')\n"
             "provenance('loaded', 'screening and re-simulation of the completed study run')"),

        md("## 8. Conclusions and limitations\n\n"
           "**What the project shows**\n\n"
           "* A small, verified IMPES simulator (18 of 18 checks pass) reproduces the "
           "analytical results taught in the lectures and couples several layers to one "
           "bottom-hole pressure.\n"
           "* Surrogates trained on the simulations predict the peak pressure build-up on "
           "reservoirs they never saw with an RMSE of about 1.2 MPa (R2 ~ 0.94) and the "
           "plume radius to about 10 m (R2 ~ 0.99), several hundred times faster than "
           "simulating -- accurate enough to screen schedules, not to certify them.\n"
           "* The error bands are empirical: their measured coverage (83-91% for a nominal "
           "90%) is reported, not assumed.\n\n"
           "**Limitations, stated plainly**\n\n"
           "* All data are synthetic. There is no field data, no history match and no "
           "field validation anywhere in this project.\n"
           "* The physics excluded in section 1 -- above all gravity -- means the plume "
           "geometry is not realistic for a real aquifer.\n"
           "* The surrogate fails most on low-permeability reservoirs, and the error band "
           "gives no protection for a reservoir unlike the training set: on study "
           "reservoir 36 all three screened schedules violated the assumed pressure limit "
           "when re-simulated, as did the constant-rate baseline.\n"
           "* Schedules are built from a permeability-dependent reference rate, so rate "
           "and permeability are correlated by construction in the dataset.\n"
           "* 55 held-out reservoirs cannot separate the best model families from one "
           "another; the ranking of the top few is not significant.\n"
           "* The saved models load only with the scikit-learn version recorded in their "
           "manifest; otherwise the loader stops and prints the command that rebuilds them.\n\n"
           "**Where to look next**\n\n"
           "| Question | File |\n"
           "|---|---|\n"
           "| Which lecture or notebook is each component from? | `docs/SOURCE_MAP.md` |\n"
           "| What exactly was assumed? | `docs/ASSUMPTIONS.md` |\n"
           "| Full method and results write-up | `docs/TECHNICAL_REPORT.md` |\n"
           "| Numbers of the run this notebook reads | `results/study/reports/RESULTS.md` |\n"
           "| Optional deeper analyses | `notebooks/supporting/` |"),
    ]


def nb01():
    return [
        md("# Supporting 1 - Sources, scope and ML-topic coverage\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "The project may use only methods, equations and data supplied in the "
           "`Models` and `Data Science and machine learning` folders. This notebook "
           "shows the actual files, the frozen topic inventory and the coverage "
           "achieved in the last run. Details: `docs/SOURCE_MAP.md`, "
           "`docs/COVERAGE_MATRIX.md`."),
        code(SETUP),
        code("import yaml\nT = yaml.safe_load((ROOT/'docs/coverage/ml_topics.yaml').read_text())\n"
             "files = pd.DataFrame([{'file': f, **v} for f, v in T['files'].items()])\n"
             "print(len(T['topics']), 'frozen topics;', len(files), 'files in the ML folder')\n"
             "display(files[files.status.str.contains('IDENTICAL')][['file','status']])"),
        md("## Topics and where they are taught"),
        code("topics = pd.DataFrame([{'id': k, 'topic': v['name'], 'n_sources': len(v['sources'])}\n"
             "                       for k, v in T['topics'].items()])\ndisplay(topics)"),
        md("## Coverage achieved in the last run (automatically verified)"),
        code("cov = json.loads((Path(cfg.paths.metrics)/'coverage.json').read_text())\n"
             "print(f\"coverage {cov['covered']}/{cov['total']} = {cov['percent']:.1f}%\")\n"
             "print('not covered:'); [print(' ', k, '-', '; '.join(v)) for k, v in cov['not_covered'].items()]"),
        md("## Are the cited source files present on this machine?\n\n"
           "The course material is **not** part of this repository. If you have your own "
           "copy, set the environment variable `SUBSURFACEML_COURSE_DIR` (or "
           "`paths.course_materials` in the config) to the folder that contains `Models/` "
           "and `Data Science and machine learning/`, and this cell checks that the files "
           "cited in `docs/SOURCE_MAP.md` exist. Nothing is read from them."),
        code("cm = cfg.paths.course_materials\n"
             "need = ['Models/1-Transmissibility.pdf', 'Models/2-Upscaling.pdf', 'Models/3-IMPES.pdf',\n"
             "        'Models/4-CO2 BL.pdf', 'Models/5-Uncertainty.pdf', 'Models/3-Advanced BL.pptx',\n"
             "        'Data Science and machine learning/Lecture08.ipynb',\n"
             "        'Data Science and machine learning/E03_geographicalspliting.ipynb']\n"
             "if cm is None:\n"
             "    print('Course material not configured (it is not distributed with this repository);'\n"
             "          ' set SUBSURFACEML_COURSE_DIR to check the cited files.')\n"
             "else:\n"
             "    for f in need:\n"
             "        print(f, '->', 'present' if (Path(cm) / f).exists() else 'NOT FOUND in ' + str(cm))"),
    ]


def nb02():
    return [
        md("# Supporting 2 - The simulator and its verification\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "Layered radial CO2-brine IMPES model (`impes.py`, from `3-IMPES.pdf`). "
           "This notebook (i) runs the two-layer case that exposed the old well "
           "coupling, (ii) reproduces the Buckley-Leverett benchmark, and (iii) "
           "reads the full verification report written by the pipeline."),
        code(SETUP + "\nfrom subsurfaceml.grid import RadialGrid, CartesianGrid1D\n"
             "from subsurfaceml.impes import TwoPhaseModel, InjectionSchedule\n"
             "from subsurfaceml.fluids import FluidProperties, RelPerm, RockProperties, bl_profile_1d, welge_shock\n"
             "from subsurfaceml.units import md_to_m2, MPA, YEAR, DAY"),
        md("## 1. One injector, two unequal layers, one bottom-hole pressure\n\n"
           "500 mD / porosity 0.25 against 20 mD / porosity 0.08 in a sealed "
           "compartment. The well equation `q_l = J_l (p_bh - p_l0)` with "
           "`sum q_l = Q` is solved together with the pressure field."),
        code("n = 30\ngrids = [RadialGrid(n=n, r_w=0.15, r_e=1500, h=10, r_near=5) for _ in range(2)]\n"
             "k = np.stack([np.full(n, md_to_m2(500)), np.full(n, md_to_m2(20))])\n"
             "phi = np.stack([np.full(n, .25), np.full(n, .08)])\n"
             "m = TwoPhaseModel(grids, k, phi, FluidProperties(), RelPerm(), RockProperties(), 15*MPA,\n"
             "                  outer_bc='closed', dt_max=30*DAY)\n"
             "t = np.linspace(0, 3*YEAR, 37)\n"
             "res = m.run(InjectionSchedule([0, 2*YEAR, 3*YEAR], [20.0, 0.0]), t)\n"
             "print('max spread of implied BHP between layers [Pa]:', res.diagnostics['max_bhp_spread_Pa'])\n"
             "print('max relative error of the total rate:', res.diagnostics['max_rate_rel_err'])\n"
             "print('CO2 mass-balance error:', res.mass_balance_error)\n"
             "fig, ax = plt.subplots(1, 2, figsize=(10, 3))\n"
             "ax[0].plot(t/YEAR, res.q_layer[:, 0]*m.fl.rho_g, label='500 mD layer')\n"
             "ax[0].plot(t/YEAR, res.q_layer[:, 1]*m.fl.rho_g, label='20 mD layer'); ax[0].legend()\n"
             "ax[0].set_xlabel('time [yr]'); ax[0].set_ylabel('layer rate [kg/s]')\n"
             "ax[1].plot(t/YEAR, (res.p_bh-15*MPA)/MPA, label='common BHP (diagnostic after shut-in)')\n"
             "ax[1].plot(t/YEAR, (res.p[:, 0, 0]-15*MPA)/MPA, '--', label='well block, layer 1')\n"
             "ax[1].plot(t/YEAR, (res.p[:, 1, 0]-15*MPA)/MPA, ':', label='well block, layer 2')\n"
             "ax[1].set_xlabel('time [yr]'); ax[1].set_ylabel('buildup [MPa]'); ax[1].legend(fontsize=7)"),
        md("The high-permeability layer takes most of the rate early; as its "
           "larger pore volume is pressurised the split drifts toward the pore-volume "
           "ratio, which is the sealed-compartment limit tested in "
           "`tests/test_well_coupling.py`. After shut-in each layer keeps its own "
           "pressure: no fluid crosses between layers through the closed well."),
        md("## 2. Buckley-Leverett (`4-CO2 BL.pdf` p.11-16)"),
        code("fl = FluidProperties(c_a=0, c_g=0); rp = RelPerm(); rk = RockProperties(c_r=0)\n"
             "L, A, ph, q = 100., 10., .2, 1e-5; T = .4*L*A*ph/q\n"
             "for nc in (100, 400):\n"
             "    g = CartesianGrid1D(n=nc, L=L, area=A)\n"
             "    mm = TwoPhaseModel([g], np.full((1, nc), md_to_m2(100)), np.full((1, nc), ph), fl, rp, rk,\n"
             "                       15*MPA, cfl=.3, max_dS=.05, dt_init=100., dt_max=T/50)\n"
             "    r = mm.run(InjectionSchedule([0, T], [q*fl.rho_g]), np.array([T]))\n"
             "    plt.plot(g.centres, r.Sg[-1, 0], label=f'IMPES {nc} cells')\n"
             "x = np.linspace(0, L, 2000)\n"
             "plt.plot(x, bl_profile_1d(rp, fl, x, T, q, A, ph, L=L), 'k--', label='Welge / MOC')\n"
             "plt.xlabel('x [m]'); plt.ylabel('S_g'); plt.legend()\n"
             "print('Welge shock saturation, fractional flow:', welge_shock(rp, fl)[:2])"),
        md("## 3. The verification report of the last pipeline run"),
        code("V = json.loads((Path(cfg.paths.metrics)/'validation.json').read_text())\n"
             "display(pd.Series(V['verdict']).to_frame('pass'))\n"
             "r7 = V['V6_V7_V8_radial_two_phase']\n"
             "for key in ('n_r', 'r_near', 'max_dS'):\n"
             "    print(key); display(pd.DataFrame(r7[key]).T[['dp_bh_max_MPa','r_plume_end_m','n_steps','wall_time_s']])\n"
             "print('strict vs relaxed time stepping'); display(pd.DataFrame(r7['cfl']).T)"),
        code("display(Image(str(Path(cfg.paths.figures)/'02_validation_convergence.png')))\n"
             "print(json.dumps(V['V10_upscaling_two_phase']['relative_error'], indent=1))"),
        md("V10 answers the question posed on `2-Upscaling.pdf` p.3-4: upscaling the "
           "layers into one (thickness-weighted arithmetic k, exact for single-phase "
           "parallel flow) keeps the pressure close but loses the layer-by-layer "
           "velocity contrast that controls the plume's leading edge."),
    ]


def nb03():
    return [
        md("# Supporting 3 - ML methods and studies in detail\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "Reads what `scripts/run_pipeline.py` wrote. Every split is grouped by "
           "reservoir realisation; the test reservoirs were used once, at the end."),
        code(SETUP + "\ndf = pd.read_csv(Path(cfg.paths.data)/'scenarios_features.csv')\n"
             "print(len(df), 'scenarios,', df.realisation_id.nunique(), 'realisations')\n"
             "print('rows per partition:', S['ml']['leakage']['rows'], '| overlaps:', S['ml']['leakage']['overlaps'])\n"
             "print(json.dumps(S['data_quality'], indent=1))"),
        md("## Model comparison (course families) and held-out errors in physical units"),
        code("rows = []\nfor t, r in S['ml']['targets'].items():\n"
             "    rows.append({'target': t, 'unit': r['unit'], 'selected': r['selected_model'],\n"
             "                 'test MAE': r['test']['MAE'], 'test RMSE': r['test']['RMSE'], 'test R2': r['test']['R2'],\n"
             "                 'max error': r['test']['max_error'], 'mean-baseline RMSE': r['mean_baseline_test']['RMSE'],\n"
             "                 'band coverage (measured)': r['error_band']['measured_coverage_test']})\n"
             "display(pd.DataFrame(rows))\n"
             "display(pd.DataFrame({t: r['model_comparison_test_rmse_physical_units'] for t, r in S['ml']['targets'].items()}))"),
        code("display(Image(str(Path(cfg.paths.figures)/'06_surrogate_parity.png')))"),
        md("## Where the surrogates fail"),
        code("for t, r in S['ml']['targets'].items():\n"
             "    h = r['difficult_cases']\n"
             "    print(f\"\\n{t}: worst 10% of test cases carry {100*h['share_of_total_abs_error_from_worst_10pct']:.0f}% of the absolute error\")\n"
             "    display(pd.DataFrame(h['worst_cases']).round(3))\n"
             "    display(pd.DataFrame(h['by_permeability_tercile']))\n"
             "    display(pd.DataFrame(h['by_schedule_intensity_tercile']))"),
        md("## Pressure-limit screening"),
        code("b = S['classifier']['binary']\n"
             "display(pd.DataFrame(b['families']).T)\n"
             "print('imbalance handling (logistic, out-of-fold, threshold 0.5):')\n"
             "display(pd.DataFrame(b['imbalance_study_logistic_oof']).T)\n"
             "for k in ('test_default_threshold', 'test_selected_threshold', 'test_regression_surrogate_thresholded'):\n"
             "    print(k, {kk: v for kk, v in b[k].items()})\n"
             "tl = S['classifier']['traffic_light']\n"
             "display(pd.DataFrame(tl['families']).T); print('test:', tl['test'])\n"
             "display(Image(str(Path(cfg.paths.figures)/'10_classifier.png')))"),
        md("## Uncertainty: Monte Carlo over the assumed prior and error sources"),
        code("for t, r in S['uncertainty']['targets'].items():\n"
             "    print(t, {k: round(v, 4) for k, v in r['monte_carlo_prior'].items() if isinstance(v, float)})\n"
             "    e = r['error_sources']; print('   shares input/surrogate/numerical %:',\n"
             "          round(e['share_input_pct'], 1), round(e['share_surrogate_pct'], 1), round(e['share_numerical_pct'], 1))"),
        md("## ML-method studies (training reservoirs only)"),
        code("st = S['studies']\n"
             "for k in ('scaler_comparison', 'missing_descriptors', 'outliers', 'polynomial', 'column_transformer',\n"
             "          'split_comparison', 'ensembles', 'normal_equation'):\n"
             "    v = st[k]; print('\\n##', k)\n"
             "    print(json.dumps({a: b for a, b in v.items() if a != 'gd_cost_history_every_500'}, indent=1, default=str)[:1500])\n"
             "print(json.dumps({k: st['feature_selection'][k] for k in st['feature_selection']}, indent=1)[:2000])\n"
             "print(json.dumps({k: {kk: vv for kk, vv in v.items() if kk != 'best'} for k, v in st['tuning_strategies'].items()}, indent=1))\n"
             "display(Image(str(Path(cfg.paths.figures)/'14_ml_studies.png')))"),
        md("## Interpretation (model behaviour, not causality) and plume shapes"),
        code("I = S['interpretation']\n"
             "display(pd.DataFrame(I['dp_bh_max_MPa']['permutation_top8']))\n"
             "if 'shap' in I: display(pd.DataFrame(I['shap']['top'][:8]))\n"
             "print(json.dumps(I['local_case'], indent=1, default=str))\n"
             "print(json.dumps(I.get('plume_shapes', {}), indent=1)[:1500])\n"
             "display(Image(str(Path(cfg.paths.figures)/'13_plume_shapes.png')))"),
        md("## Cost"),
        code("print(json.dumps(S['speed'], indent=1))"),
    ]


def nb04():
    return [
        md("# Supporting 4 - Schedule screening on an unseen reservoir\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "Monte Carlo screening (`5-Uncertainty.pdf` p.44-45) with the saved "
           "surrogates, then re-simulation. Limits are stated assumptions."),
        code(SETUP + "\nfrom subsurfaceml.predict import Predictor\n"
             "from subsurfaceml.optimise import SurrogateBundle, optimise_schedule, resimulate\n"
             "from subsurfaceml.scenarios import sample_realisations\n"
             "P = Predictor(cfg)   # verified artifacts; raises with a rebuild command if missing\n"
             "b = SurrogateBundle(features=P.surrogates['dp_bh_max_MPa'].features,\n"
             "    pressure=P.surrogates['dp_bh_max_MPa'], plume=P.surrogates['r_plume_m95_m'],\n"
             "    band_pressure=P.bands['dp_bh_max_MPa'], band_plume=P.bands['r_plume_m95_m'])\n"
             "rid = P.manifest['test_realisation_ids'][0]\n"
             "r = {x.realisation_id: x for x in sample_realisations(cfg)}[rid]\nprint(r)"),
        code("s = optimise_schedule(cfg, r, b)\n"
             "print(s['n_feasible'], 'of', s['n_candidates'], 'candidates predicted feasible')\n"
             "rows = [resimulate(cfg, r, s['baseline']['rates_kg_s'], 'constant-rate baseline')]\n"
             "rows += [resimulate(cfg, r, c['rates_kg_s'], f'screened {i}') for i, c in enumerate(s['shortlist'][:3])]\n"
             "display(pd.DataFrame(rows)[['label','rates_kg_s','sim_mass_injected_Mt','sim_dp_bh_max_MPa',\n"
             "                           'sim_r_plume_m95_m','violates_pressure','violates_plume']])"),
        md("## All unseen reservoirs of the pipeline run"),
        code("o = S['optimisation']\n"
             "display(pd.DataFrame(o['per_realisation']))\n"
             "print({k: o[k] for k in ('median_improvement_pct','n_realisations_improved','n_realisations_compared',\n"
             "       'n_screened_violating','n_screened_resimulated','n_baselines_violating','n_failed_resimulations')})\n"
             "display(Image(str(Path(cfg.paths.figures)/'15_schedule_screening.png')))"),
    ]


def nb05():
    return [
        md("# Supporting 5 - Worked example: inputs -> simulation -> prediction -> evaluation\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "Input file: `examples/worked_example_input.json` (assumed generic values, "
           "not a real site). The same steps are available from the command line:\n\n"
           "```\nsubsurfaceml simulate --config config/demo.yaml --input examples/worked_example_input.json\n"
           "subsurfaceml predict  --config config/demo.yaml --input examples/worked_example_input.json\n```"),
        code(SETUP + "\nfrom subsurfaceml.predict import Predictor, realisation_from_dict\n"
             "from subsurfaceml.scenarios import make_schedule, run_scenario, reference_rate\n"
             "from subsurfaceml.features import raw_inputs, features_for_schedules\n"
             "from subsurfaceml.units import MPA, YEAR\n"
             "case = json.loads((ROOT/'examples/worked_example_input.json').read_text())\n"
             "r = realisation_from_dict(case['reservoir']); rates = np.array(case['rates_kg_s'])\n"
             "print(r); print('rates [kg/s]:', rates)"),
        md("## Step 1 - inputs the surrogate sees (the single feature path)\n\n"
           "`raw_inputs` builds the layered rock with the realisation's seed, the "
           "closed-form reference rate and the end-point mobility ratio with this "
           "reservoir's own `krg0`; `engineer` adds log-transforms, flow capacity, "
           "pore volume and schedule-shape descriptors."),
        code("raw = raw_inputs(cfg, r, rates)\n"
             "print({k: raw[k] for k in ('V_DP_layers','q_ref_kg_s','endpoint_mobility_ratio','planned_mass_kg')})\n"
             "X = features_for_schedules(cfg, r, rates[None, :]); display(X.T.rename(columns={0: 'value'}))"),
        md("## Step 2 - simulate (the reference answer)"),
        code("o = run_scenario(cfg, r, make_schedule(cfg, r, rates), want_series=True)\n"
             "w, ts = o['row'], o['series']\n"
             "sim = {'dp_bh_max_MPa': w['dp_bh_max_Pa']/MPA, 'r_plume_m95_m': w['r_plume_m95_m'],\n"
             "       'sweep_efficiency': w['sweep_efficiency']}\n"
             "print(sim, '| wall time', round(w['wall_time_s'], 2), 's | mass balance', w['mass_balance_error'])\n"
             "fig, ax = plt.subplots(1, 2, figsize=(10, 3))\n"
             "ax[0].plot(ts.t_s/YEAR, ts.dp_bh_Pa/MPA); ax[0].axhline(cfg.optim.p_limit_MPa-cfg.solver.p_init_MPa, c='r', ls='--')\n"
             "ax[0].set_xlabel('time [yr]'); ax[0].set_ylabel('BHP buildup [MPa]')\n"
             "ax[1].plot(ts.t_s/YEAR, ts.r_plume_m95_m); ax[1].set_xlabel('time [yr]'); ax[1].set_ylabel('plume radius (95% mass) [m]')"),
        md("## Step 3 - predict with the saved surrogates"),
        code("P = Predictor(cfg)\nout = P.predict(r, rates[None, :])\n"
             "rows = []\nfor t in sim:\n"
             "    o_ = out[t]; p, lo, hi = o_['pred'][0], o_['band_low'][0], o_['band_high'][0]\n"
             "    rows.append({'quantity': t, 'simulated': sim[t], 'predicted': p, 'error': p - sim[t],\n"
             "                 'relative error %': 100*(p - sim[t])/sim[t], 'band P5': lo, 'band P95': hi,\n"
             "                 'inside band': lo <= sim[t] <= hi, 'unit': o_['unit']})\n"
             "display(pd.DataFrame(rows))\n"
             "e = out['exceeds_pressure_limit']\n"
             "print('classifier flag (exceeds limit):', bool(e['flag'][0]), '| simulated exceedance:',\n"
             "      sim['dp_bh_max_MPa'] > e['dp_limit_MPa'])"),
        md("## Step 4 - evaluate: how does this case compare with the test-set error?"),
        code("for t in sim:\n"
             "    te = S['ml']['targets'][t]['test']\n"
             "    print(f\"{t}: this case |error| = {abs(out[t]['pred'][0]-sim[t]):.4g}; test MAE {te['MAE']:.4g}, \"\n"
             "          f\"max {te['max_error']:.4g} {S['ml']['targets'][t]['unit']}\")"),
        md("**Reading this result (demo models, 2026-09-20 run).** Pressure build-up "
           "and sweep are predicted within 3% and inside their bands. The plume radius "
           "is over-predicted by ~25 m (8%), about five times the test-set MAE and just "
           "outside the P5-P95 band: a measured coverage of ~92% means roughly one case "
           "in twelve falls outside, and this is one of them. It is also why proposals "
           "from the screening step are always re-simulated."),
        md("## Step 5 - what-if: scale the whole schedule"),
        code("f = np.linspace(.4, 2, 33)\n"
             "pred = P.predict(r, np.outer(f, rates))['dp_bh_max_MPa']\n"
             "plt.plot(f, pred['pred']); plt.fill_between(f, pred['band_low'], pred['band_high'], alpha=.3)\n"
             "plt.axhline(cfg.optim.p_limit_MPa-cfg.solver.p_init_MPa, c='r', ls='--'); plt.axvline(1, c='grey')\n"
             "plt.xlabel('schedule scaled by'); plt.ylabel('predicted dp_bh_max [MPa]')"),
    ]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--execute", action="store_true")
    a = ap.parse_args()
    SUP.mkdir(parents=True, exist_ok=True)
    books = {NB / "00_START_HERE.ipynb": nb00(),
             SUP / "s1_sources_and_coverage.ipynb": nb01(),
             SUP / "s2_simulator_verification.ipynb": nb02(),
             SUP / "s3_ml_methods_and_studies.ipynb": nb03(),
             SUP / "s4_schedule_screening.ipynb": nb04(),
             SUP / "s5_worked_example.ipynb": nb05()}
    for path, cells in books.items():
        nb = nbf.v4.new_notebook(cells=cells)
        nb.metadata["kernelspec"] = {"name": "python3", "display_name": "Python 3",
                                     "language": "python"}
        nbf.write(nb, path)
        print("wrote", path.relative_to(ROOT))
    if a.execute:
        from nbconvert.preprocessors import ExecutePreprocessor
        for path in books:
            nb = nbf.read(path, as_version=4)
            ExecutePreprocessor(timeout=1800, kernel_name="python3").preprocess(
                nb, {"metadata": {"path": str(path.parent)}})
            nbf.write(nb, path)
            print("executed", path.relative_to(ROOT))


if __name__ == "__main__":
    sys.exit(main())
