#!/usr/bin/env python
"""(Re)write the notebooks from this script so their code stays in one
reviewed place.  Execute them afterwards with

    python scripts/make_notebooks.py --execute

There is one entry point, ``notebooks/00_START_HERE.ipynb`` (the walkthrough),
and five optional supporting notebooks in ``notebooks/supporting/``.  The
notebooks call the package code only; they re-implement nothing.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks"
SUP = NB / "supporting"

# One setup cell for every notebook.  ``CONFIG`` selects which completed run the
# notebook reads: 'study' is the large run quoted in the report, 'demo' the small
# one anybody can reproduce in ten minutes.
HEADER = """import sys, json, time
from pathlib import Path
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'pyproject.toml').exists())
sys.path.insert(0, str(ROOT / 'src'))
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from IPython.display import Image, display
from subsurfaceml.config import load_config

CONFIG = '{config}'                 # which completed run this notebook reads
cfg = load_config(ROOT / 'config' / f'{{CONFIG}}.yaml')
S = json.loads((Path(cfg.paths.metrics) / 'summary.json').read_text())
pd.set_option('display.max_colwidth', 80)
plt.rcParams.update({{'figure.dpi': 110, 'axes.grid': True, 'grid.alpha': .3,
                     'font.size': 9, 'figure.constrained_layout.use': True}})


def provenance(kind, what):
    \"\"\"Label every result: read from a finished run, or computed right here.\"\"\"
    label = {{'loaded': 'LOADED from the completed ' + CONFIG + ' run',
             'computed': 'COMPUTED NOW in this notebook session'}}[kind]
    print(f'[{{label}}]  {{what}}')"""

SETUP = HEADER.format(config="demo")
SETUP_STUDY = HEADER.format(config="study")


def md(s):
    return nbf.v4.new_markdown_cell(s)


def code(s):
    return nbf.v4.new_code_cell(s)


def nb00():
    """The one notebook a reader should open first."""
    return [
        md("# CO2 storage in a layered saline aquifer: verified simulator, hybrid surrogate, verified screening\n\n"
           "**The question.** In a sealed, layered saline aquifer, can a cheap surrogate, "
           "trained on simulations, predict the peak pressure build-up at the injection well "
           "for reservoirs it has never seen -- reliably enough, and with honest enough "
           "uncertainty, to screen injection schedules against a pressure limit, with the "
           "simulator confirming every recommendation?\n\n"
           "**What this notebook is.** The whole study, in order. It runs a simulation, "
           "re-computes the key numbers from the saved models, and reads the rest from the "
           "finished run. Every output is labelled either\n\n"
           "* `[LOADED from the completed study run]` -- read from `results/study/`, produced by "
           "`scripts/run_pipeline.py`, `scripts/run_experiments.py` and "
           "`scripts/run_model_form.py`, or\n"
           "* `[COMPUTED NOW in this notebook session]` -- calculated while you run these cells.\n\n"
           "**Plan**\n\n"
           "1. Purpose, scope and assumptions\n"
           "2. One simulation, run here\n"
           "3. Verification, numerical error and model-form error\n"
           "4. Data roles: development, fresh test, distribution shift\n"
           "5. Why the published surrogate failed where it did\n"
           "6. The analytical ROM and the hybrid surrogate; the ablation\n"
           "7. Results on the untouched test reservoirs and under shift, re-checked here\n"
           "8. Intervals: what they cover and what they do not\n"
           "9. Verification-gated schedule screening\n"
           "10. Conclusions and limitations\n\n"
           "**All data are synthetic**, generated by the simulator in this repository. "
           "Nothing is calibrated to, or validated against, a real site."),
        code(SETUP_STUDY + "\n\n"
             "provenance('loaded', f\"run of {S['config_file']} started {S['started']}, \"\n"
             "           f\"{S['total_wall_seconds']/60:.1f} min wall, python \"\n"
             "           f\"{S['environment']['python']}, scikit-learn {S['environment']['scikit_learn']}\")\n"
             "EXP = Path(cfg.paths.results) / 'experiments'"),

        md("## 1. Purpose, scope and assumptions\n\n"
           "One rate-controlled injector sits at the centre of a sealed, cylindrical "
           "compartment of four horizontal layers. Each layer has its own permeability and "
           "porosity; all layers share **one bottom-hole pressure**, solved together with the "
           "pressure field. The production simulator leaves out:\n\n"
           "| Left out | Consequence | Quantified? |\n"
           "|---|---|---|\n"
           "| Gravity / buoyancy | no gravity override under the caprock | yes, with a separate r-z model (section 3) |\n"
           "| Vertical crossflow between layers | layers communicate only through the well | yes, same r-z model |\n"
           "| Dissolution and residual trapping | storage security cannot be assessed | no |\n"
           "| Capillary pressure (`P_c = 0`) | no capillary smearing or entry pressure | no |\n"
           "| Non-radial geometry, faults, more wells | not a field model | no |\n\n"
           "The 9 MPa build-up limit and the 400 m plume-radius limit are **modelling "
           "assumptions** that define a screening question; nothing about fracture pressure, "
           "caprock integrity or leakage is modelled. Full list: `docs/ASSUMPTIONS.md`."),
        code("c = S['config']\n"
             "print('development reservoirs  :', c['scenarios']['n_realisations'], 'x',\n"
             "      c['scenarios']['n_schedules_per_realisation'], 'schedules')\n"
             "print('radial cells / layers   :', c['grid']['n_r'], '/', c['grid']['n_layers'])\n"
             "print('injection / total [yr]  :', c['schedule']['t_inject_years'], '/',\n"
             "      c['schedule']['t_total_years'], 'in', c['schedule']['n_periods'], 'rate periods')\n"
             "print('assumed limits          :', cfg.optim.p_limit_MPa - cfg.solver.p_init_MPa,\n"
             "      'MPa build-up,', cfg.optim.r_plume_limit_m, 'm plume radius')\n"
             "print('revised design          :', {k: c['ml'][k] for k in ('feature_set', 'feature_set_plume', 'feature_set_sweep',\n"
             "      'pressure_model', 'interval_method')})\n"
             "provenance('loaded', 'configuration of the completed run')"),

        md("## 2. One simulation, run here\n\n"
           "IMPES (implicit pressure, explicit saturation) on a radial grid with upstream "
           "mobilities and harmonic transmissibilities (`3-IMPES.pdf`, "
           "`1-Transmissibility.pdf`). The cell takes the first reservoir of the fresh test set, "
           "one of its schedules, and simulates it from scratch."),
        code("from subsurfaceml.final_eval import eval_realisations\n"
             "from subsurfaceml.scenarios import sample_schedules, run_scenario\n"
             "from subsurfaceml.units import MPA, YEAR\n"
             "ctest, test_reals = eval_realisations(cfg, 'final_test')\n"
             "r = test_reals[0]                          # generated after the design was fixed\n"
             "sched = sample_schedules(ctest, r)[0]\n"
             "print('reservoir', r.realisation_id, ': median k =', round(r.k_median_mD), 'mD, V_DP =',\n"
             "      round(r.V_DP, 2), ', thickness =', round(r.h_total_m), 'm')\n"
             "print('injection rates [kg/s]:', np.round(sched['rates_kg_s'], 2))\n"
             "t0 = time.perf_counter()\n"
             "out = run_scenario(ctest, r, sched, want_series=True)\n"
             "row, series = out['row'], out['series']\n"
             "provenance('computed', f\"one simulation in {time.perf_counter()-t0:.1f} s \"\n"
             "           f\"(CO2 mass-balance error {row['mass_balance_error']:.1e})\")\n"
             "print('peak pressure build-up    :', round(row['dp_bh_max_Pa']/MPA, 2), 'MPa')\n"
             "print('plume radius (95% of mass):', round(row['r_plume_m95_m']), 'm')\n"
             "fig, ax = plt.subplots(1, 2, figsize=(9.5, 3.1))\n"
             "ax[0].plot(series.t_s/YEAR, series.dp_bh_Pa/MPA, color='#1f6f8b')\n"
             "ax[0].axhline(cfg.optim.p_limit_MPa - cfg.solver.p_init_MPa, color='tab:red', ls='--', lw=1,\n"
             "              label='assumed limit')\n"
             "ax[0].set_xlabel('Time [years]'); ax[0].set_ylabel('Bottom-hole pressure build-up [MPa]')\n"
             "ax[0].legend(fontsize=8)\n"
             "ax[1].plot(series.t_s/YEAR, series.r_plume_m95_m, color='#d1495b')\n"
             "ax[1].set_xlabel('Time [years]'); ax[1].set_ylabel('Plume radius, 95 % of CO$_2$ mass [m]')\n"
             "plt.show()"),

        md("## 3. Verification, numerical error and model-form error\n\n"
           "*Verification* asks whether the equations are solved correctly; it is not "
           "validation against measurements (there are none). The pipeline refuses to "
           "generate data if any check fails. V12 and V13 check the quantity the surrogates "
           "learn -- the two-phase simulator's bottom-hole pressure -- against the "
           "pseudo-steady-state solution of a bounded reservoir."),
        code("verdict = {k: v for k, v in S['validation_verdict'].items() if k != 'ALL_PASS'}\n"
             "print(f\"{sum(verdict.values())} of {len(verdict)} verification checks pass\")\n"
             "V = json.loads((Path(cfg.paths.metrics)/'validation.json').read_text())\n"
             "pss = V['V12_V13_pss_well_pressure']\n"
             "display(pd.DataFrame({k: {'simulated build-up [MPa]': v['sim_dp_bh_MPa'],\n"
             "                          'PSS analytical [MPa]': v['pss_analytic_dp_MPa'],\n"
             "                          'relative difference': v['rel_err_sim_vs_pss'],\n"
             "                          'ROM relative difference': v['rel_err_rom_vs_pss']}\n"
             "                      for k, v in pss.items()}).T)\n"
             "provenance('loaded', 'results/study/metrics/validation.json')"),
        md("**Discretisation error of the training data.** A stratified sample of the "
           "development cases is re-simulated with the grid, the well block and the time step "
           "refined. The question is whether the numerical error of the *targets* is small "
           "compared with the surrogate error, and whether it can change a pressure-limit label."),
        code("N = S['numerics']\n"
             "rows = {t: N['targets'][t]['production_minus_fine'] for t in N['targets']}\n"
             "display(pd.DataFrame(rows).T[['median_rel', 'p90_rel', 'max_rel', 'max_abs', 'n']])\n"
             "print('pressure-limit labels changed by refinement:', N['pressure_limit_label_flips']['n_flipped'],\n"
             "      'of', N['pressure_limit_label_flips']['n_compared'])\n"
             "display(Image(str(Path(cfg.paths.figures)/'17_numerics_dataset_cases.png')))\n"
             "provenance('loaded', 'results/study/metrics/numerics_summary.json')"),
        md("**Screen of every case for a transient peak.** A sample cannot reveal a rare "
           "failure mode, so every development, test and shift case was screened for a peak "
           "build-up that occurs between the stored reporting times -- a transient right after "
           "injection starts or the rate rises, whose height depends on the well-block size. "
           "Flagged cases were re-simulated with the discretisation refined. The error always "
           "over-states the peak."),
        code("PS = json.loads((EXP/'peak_screen.json').read_text())\n"
             "rows = {}\n"
             "for s_, d_ in PS['sets'].items():\n"
             "    ch = [c['rel_change_fine'] for c in d_['flagged_cases']]\n"
             "    rows[s_] = {'cases': d_['n_cases'], 'flagged': d_['n_flagged'],\n"
             "               'refined peak change, min': min(ch) if ch else None,\n"
             "               'refined peak change, max': max(ch) if ch else None,\n"
             "               'limit labels changed': d_['n_limit_label_changes']}\n"
             "display(pd.DataFrame.from_dict(rows, orient='index').round(3))\n"
             "for s_ in ('final_test', 'shift'):\n"
             "    r_ = PS['sets'][s_]['revised_surrogate']\n"
             "    print(f\"{s_}: revised surrogate RMSE {r_['stored_targets']['RMSE']:.3f} MPa with the stored \"\n"
             "          f\"targets, {r_['flagged_targets_refined']['RMSE']:.3f} MPa with the flagged cases refined\")\n"
             "provenance('loaded', 'results/study/experiments/peak_screen.json')"),
        md("**Model-form error.** A separate radial-vertical model (`rz.py`) adds buoyancy "
           "and vertical crossflow and otherwise keeps everything the same (it reduces to the "
           "layered model when both are switched off; `tests/test_rz.py`). The change of each "
           "target measures what the layered, no-gravity assumption costs. `k_v/k_h = 0.1` is "
           "an assumed value."),
        code("MF = json.loads((EXP/'model_form_summary.json').read_text())\n"
             "display(pd.DataFrame({v: {t: MF['targets'][v][t]['median_rel_change'] for t in\n"
             "      ('dp_bh_max_MPa', 'r_plume_m95_m', 'sweep_efficiency')} for v in MF['targets']}).T\n"
             "        .rename(columns=lambda c: c + ' (median rel. change)'))\n"
             "print('pressure-limit labels changed:', {v: MF['labels'][v]['n_label_changes'] for v in MF['labels']})\n"
             "display(Image(str(Path(cfg.paths.figures)/'19_model_form_error.png')))\n"
             "provenance('loaded', 'results/study/experiments/model_form_summary.json')"),

        md("## 4. Data roles: development, fresh test, distribution shift\n\n"
           "The unit of learning is the **reservoir realisation**: its schedules share one "
           "reservoir, so every split and every cross-validation fold is by whole reservoir. "
           "The published run's 55 test reservoirs were inspected while this revision was "
           "developed, so they now train; the test reservoirs below were generated after every "
           "modelling choice had been fixed (`docs/EVALUATION_PROTOCOL.md`)."),
        code("print('reservoirs per role :', S['ml']['leakage']['reservoirs'])\n"
             "print('rows per role       :', S['ml']['leakage']['rows'])\n"
             "print('overlaps            :', S['ml']['leakage']['overlaps'], '(all must be 0)')\n"
             "print('disjoint sets       :', S['evaluation_sets']['disjoint'])\n"
             "for k, v in S['evaluation_sets']['provenance'].items():\n"
             "    print(f\"{k:10s}: seed {v['seed']}, {v['n_realisations']} reservoirs, median k in {v['k_median_mD_range']} mD,\"\n"
             "          f\" {v['n_success']} ok / {v['n_failed']} failed\")\n"
             "provenance('loaded', 'split and evaluation-set records of the completed run')"),

        md("## 5. Why the published surrogate failed where it did\n\n"
           "The published surrogate described a reservoir by the parameters of its sampling "
           "prior -- median permeability and target Dykstra-Parsons coefficient. The simulator "
           "uses four *realised* layers drawn from that prior. With four draws, the realised "
           "layers can be far tighter or more permeable than the parameters imply. The cell "
           "computes, for the published run's worst pressure cases, the realised arithmetic-mean "
           "permeability against what the prior parameters lead one to expect."),
        code("from subsurfaceml.evaluation import prior_mean_arith_k\n"
             "dev = pd.read_csv(Path(cfg.paths.data)/'scenarios_features.csv')\n"
             "worst = ['R0172_S+00', 'R0039_S+03', 'R0036_S+02', 'R0150_S+03']\n"
             "w = dev.set_index('scenario_id').loc[worst]\n"
             "tab = pd.DataFrame({'simulated build-up [MPa]': w.dp_bh_max_MPa,\n"
             "                    'median k (prior) [mD]': w.k_median_mD,\n"
             "                    'V_DP (prior)': w.V_DP, 'V_DP realised': w.V_DP_layers,\n"
             "                    'expected mean k [mD]': prior_mean_arith_k(w.k_median_mD, w.V_DP),\n"
             "                    'realised mean k [mD]': w.k_arith_mean_m2 / 9.869233e-16}).round(2)\n"
             "tab['realised / expected'] = (tab['realised mean k [mD]'] / tab['expected mean k [mD]']).round(2)\n"
             "display(tab)\n"
             "provenance('computed', 'from the development data set; the published predictions for these '\n"
             "           'cases were 17.6, 18.8, 7.9 and 11.5 MPa (results/published_2026-09-20/)')"),

        md("## 6. The analytical ROM and the hybrid surrogate; the ablation\n\n"
           "`rom.py` treats each realised layer as a sealed tank in pseudo-steady state, all "
           "connected to one bottom-hole pressure with the simulator's injector-only rule. It "
           "uses no simulator output. The hybrid surrogate learns only the correction factor the "
           "ROM needs: `ln(dp) = ln(dp_ROM) + g(x)`. The ablation compares variants with nested, "
           "reservoir-grouped cross-validation on the development reservoirs only, with identical "
           "folds and search budgets."),
        code("from subsurfaceml.evaluation import point_metrics\n"
             "rom_dp = 10 ** dev['log10_rom_dp_MPa']\n"
             "m = point_metrics(dev['dp_bh_max_MPa'], rom_dp)\n"
             "provenance('computed', f\"ROM alone on all {m['n']} development cases: RMSE {m['RMSE']:.3f} MPa, \"\n"
             "           f\"MAE {m['MAE']:.3f} MPa, worst under-prediction {m['worst_underprediction']:.2f} MPa\")\n"
             "A = json.loads((EXP/'ablation_summary.json').read_text())\n"
             "met = A['targets']['dp_bh_max_MPa']['metrics']\n"
             "keys = ['RMSE', 'MAE', 'p95_abs_error', 'worst_underprediction', 'max_abs_error']\n"
             "tab = pd.DataFrame({v: {k: met[v][k] for k in keys} for v in met}).T.round(3)\n"
             "tab['dRMSE vs V0, 95% CI'] = [str([round(x, 3) for x in met[v]['vs_V0_published_features']['RMSE']['ci95']])\n"
             "                              if 'vs_V0_published_features' in met[v] else '' for v in met]\n"
             "display(tab)\n"
             "print('decisions (pre-declared rules):', A['decisions'])\n"
             "display(Image(str(Path(cfg.paths.figures)/'16_ablation_pressure.png')))\n"
             "provenance('loaded', 'results/study/experiments/ablation_summary.json')"),

        md("## 7. Results on the untouched test reservoirs and under shift, re-checked here\n\n"
           "Three things are compared on the same reservoirs: the revised design, the published "
           "approach retrained on the same development reservoirs, and the published models as "
           "released. The second cell does not trust the table: it loads the saved revised "
           "models, re-predicts the fresh test reservoirs and recomputes the metrics."),
        code("rows = []\n"
             "for t, res in S['ml']['targets'].items():\n"
             "    for d, dd in res['designs'].items():\n"
             "        for s_ in ('test', 'shift'):\n"
             "            p = dd['evaluation'][s_]['point']\n"
             "            rows.append({'target': t, 'design': d, 'set': s_, 'model': dd['selected_model'],\n"
             "                         'RMSE': p['RMSE'], 'MAE': p['MAE'], 'R2': p['R2'],\n"
             "                         'P95 |error|': p['p95_abs_error'],\n"
             "                         'worst under': p['worst_underprediction']})\n"
             "display(pd.DataFrame(rows).set_index(['target', 'set', 'design']).round(4))\n"
             "b = S['ml']['targets']['dp_bh_max_MPa']['bootstrap']\n"
             "for k, v in b.items():\n"
             "    print(k, ': dRMSE', round(v['RMSE']['difference_b_minus_a'], 4), 'MPa, 95% CI',\n"
             "          [round(x, 4) for x in v['RMSE']['ci95']])\n"
             "provenance('loaded', 'final evaluation of the completed study run')"),
        code("from subsurfaceml.predict import Predictor\n"
             "P = Predictor(cfg)           # verified artifacts; refuses a mismatched version\n"
             "test = pd.read_csv(Path(cfg.paths.data)/'final_test_scenarios.csv')\n"
             "check = []\n"
             "for t, model in P.surrogates.items():\n"
             "    m = point_metrics(test[t], model.predict(test))\n"
             "    check.append({'target': t, 'n': m['n'], 'RMSE recomputed': round(m['RMSE'], 4),\n"
             "                  'RMSE reported': round(S['ml']['targets'][t]['test']['RMSE'], 4),\n"
             "                  'R2 recomputed': round(m['R2'], 4),\n"
             "                  'R2 reported': round(S['ml']['targets'][t]['test']['R2'], 4)})\n"
             "display(pd.DataFrame(check).set_index('target'))\n"
             "provenance('computed', 'predictions and metrics recomputed from the saved models')"),
        code("display(Image(str(Path(cfg.paths.figures)/'06_surrogate_parity.png')))\n"
             "display(Image(str(Path(cfg.paths.figures)/'08_errors_dp_bh_max_MPa.png')))\n"
             "sg = S['ml']['targets']['dp_bh_max_MPa']['designs']\n"
             "names = {'k_group': 'median permeability tercile',\n"
             "         'mismatch_group': 'realised vs prior permeability',\n"
             "         'near_limit': 'distance to the 9 MPa limit'}\n"
             "rows = [{'grouping': names.get(g, g), 'subgroup': lv, 'n': m['n'], 'design': d,\n"
             "         'RMSE [MPa]': m['RMSE'], 'worst under-prediction [MPa]': m['worst_underprediction']}\n"
             "        for d in ('revised', 'published_approach')\n"
             "        for g, grp in sg[d]['evaluation']['test']['subgroups'].items()\n"
             "        for lv, m in grp.items()]\n"
             "display(pd.DataFrame(rows).pivot_table(index=['grouping', 'subgroup', 'n'], columns='design',\n"
             "        values=['RMSE [MPa]', 'worst under-prediction [MPa]']).round(3))\n"
             "provenance('loaded', 'subgroup errors on the test reservoirs')"),

        md("## 8. Intervals: what they cover and what they do not\n\n"
           "The interval method was chosen on development data by a pre-declared rule. "
           "*Case coverage* is the share of cases inside their interval; *whole-reservoir "
           "coverage* is the share of reservoirs with every schedule inside -- the property "
           "the screening relies on. The reservoir-level conformal construction supports a "
           "statement only for reservoirs drawn like the calibration reservoirs."),
        code("ev = S['ml']['targets']['dp_bh_max_MPa']['designs']['revised']['evaluation']\n"
             "rows = []\n"
             "for s_ in ('test', 'shift'):\n"
             "    for meth, v in ev[s_]['intervals'].items():\n"
             "        rows.append({'set': s_, 'method': meth, 'case coverage': v['case_coverage'],\n"
             "                     'reservoirs fully covered': v['reservoir_all_covered'],\n"
             "                     'mean width [MPa]': v['mean_width'],\n"
             "                     'missed exceedances (upper edge)': v['limit_upper']['missed_exceedances'],\n"
             "                     'exceedances': v['limit_upper']['n_exceeding']})\n"
             "display(pd.DataFrame(rows).set_index(['set', 'method']).round(3))\n"
             "print('domain check flags', round(100*ev['shift']['domain']['share_reservoirs_flagged']),\n"
             "      '% of shift reservoirs and', round(100*ev['test']['domain']['share_reservoirs_flagged']),\n"
             "      '% of test reservoirs')\n"
             "display(Image(str(Path(cfg.paths.figures)/'18_interval_coverage.png')))\n"
             "provenance('loaded', 'interval evaluation, peak build-up, revised design')"),

        md("## 9. Verification-gated schedule screening\n\n"
           "No schedule is recommended unless the simulator has run it and it met both stated "
           "limits. Five methods share a budget of four simulations per reservoir (three for the "
           "published method, as published); the baseline every gain is measured against is a "
           "simulator-only constant-rate search."),
        code("SC = S['screening']\n"
             "rows = []\n"
             "for s_, d in SC['by_set'].items():\n"
             "    for meth, v in d['methods'].items():\n"
             "        rows.append({'set': s_, 'method': meth, 'reservoirs': d['n_reservoirs'],\n"
             "                     'verified': v['n_verified'], 'no feasible found': v['n_no_feasible_found'],\n"
             "                     'first simulated proposal violated': v['first_simulated_schedule_violates'],\n"
             "                     'median mass vs constant [%]': v['median_mass_vs_constant_pct'],\n"
             "                     'mean simulations': v['mean_simulations']})\n"
             "display(pd.DataFrame(rows).set_index(['set', 'method']).round(2))\n"
             "display(Image(str(Path(cfg.paths.figures)/'15_schedule_screening.png')))\n"
             "provenance('loaded', 'results/study/metrics/screening_recommendations.csv')"),

        md("## 10. Conclusions and limitations\n\n"
           "**What the study shows** (numbers in the cells above, from the completed study run)\n\n"
           "* The simulator passes 21 verification checks, including its two-phase bottom-hole "
           "pressure against the pseudo-steady-state solution, and the discretisation error of the "
           "training targets is small for pressure (section 3).\n"
           "* The published surrogate's largest pressure errors had one cause: it described each "
           "reservoir by the parameters of its sampling prior rather than by the realised layers "
           "the simulator used (section 5). More model capacity did not help; correcting the "
           "inputs and learning only the correction to an analytical ROM did (section 6).\n"
           "* On reservoirs generated after every choice was fixed, the hybrid surrogate roughly "
           "halves the peak-pressure RMSE of the published approach trained on the same data, "
           "lowers its worst under-prediction, and misses no exceedance of the assumed limit "
           "(section 7).\n"
           "* Intervals calibrated by reservoir are about three times narrower than the published "
           "band at similar whole-reservoir coverage; pooled calibration under-covers whole "
           "reservoirs, and no interval keeps its coverage under the distribution shift (section 8).\n"
           "* Every recommended schedule is verified by the simulator. Shaped schedules gain a few "
           "per cent over the best constant rate; the analytical ROM ranks schedules as well as "
           "the learned surrogate, whose value is in accurate predictions and safe first "
           "proposals (section 9).\n\n"
           "**Limitations, stated plainly**\n\n"
           "* All data are synthetic; there is no field data and no field validation.\n"
           "* The data-generating model has no gravity or crossflow; adding them changes the "
           "peak build-up by a few per cent but the plume radius by a factor of about two, so "
           "plume results describe the layered model only (section 3).\n"
           "* The 9 MPa build-up limit and the 400 m plume limit are modelling assumptions.\n"
           "* Interval statements apply to reservoirs drawn like the calibration reservoirs; the "
           "domain check flags reservoirs outside the training population, and the screening "
           "then falls back to the simulator.\n"
           "* The most extreme build-up case remains under-predicted by about 15 %.\n\n"
           "**Where to look next**\n\n"
           "| Question | File |\n"
           "|---|---|\n"
           "| What was decided before the test data existed? | `docs/EVALUATION_PROTOCOL.md` |\n"
           "| Full method and results | `docs/TECHNICAL_REPORT.md` |\n"
           "| Which source is each component from? | `docs/SOURCE_MAP.md` |\n"
           "| What exactly was assumed? | `docs/ASSUMPTIONS.md` |\n"
           "| Every number of the run | `results/study/reports/RESULTS.md` |\n"
           "| Optional deeper analyses | `notebooks/supporting/` |"),
    ]


def nb01():
    return [
        md("# Supporting 1 - Sources and scope\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "The 2026-09-20 version used only methods supplied in the course folders `Models` and "
           "`Data Science and machine learning`. The October 2026 revision adds a few components "
           "from outside that material, each with its primary source in `docs/SOURCE_MAP.md` §4. "
           "The topic-coverage record of the 2026-09-20 version is archived in "
           "`docs/archive/2026-09-20_course_coverage/` and is not regenerated."),
        code(SETUP),
        code("txt = (ROOT/'docs/SOURCE_MAP.md').read_text()\n"
             "sec4 = txt[txt.index('## 4.'):]\n"
             "print(sec4[:3000])"),
        md("## The archived topic inventory (2026-09-20)"),
        code("import yaml\nA = ROOT/'docs/archive/2026-09-20_course_coverage'\n"
             "T = yaml.safe_load((A/'coverage/ml_topics.yaml').read_text())\n"
             "topics = pd.DataFrame([{'id': k, 'topic': v['name'], 'n_sources': len(v['sources'])}\n"
             "                       for k, v in T['topics'].items()])\n"
             "print(len(topics), 'frozen topics (2026-09-20)'); display(topics.head(12))\n"
             "cov = json.loads((A/'coverage_study.json').read_text())\n"
             "print(f\"2026-09-20 coverage: {cov['covered']}/{cov['total']} = {cov['percent']:.1f}%\")"),
        md("## Are the cited source files present on this machine?\n\n"
           "The course material is **not** part of this repository. If you have your own "
           "copy, set the environment variable `SUBSURFACEML_COURSE_DIR` (or "
           "`paths.course_materials` in the config) to the folder that contains `Models/` "
           "and `Data Science and machine learning/`, and this cell checks that the files "
           "cited in `docs/SOURCE_MAP.md` exist. Nothing is read from them."),
        code("cm = cfg.paths.course_materials\n"
             "need = ['Models/1-Transmissibility.pdf', 'Models/2-Upscaling.pdf', 'Models/3-IMPES.pdf',\n"
             "        'Models/4-CO2 BL.pdf', 'Models/5-Uncertainty.pdf', 'Models/3-Advanced BL.pptx',\n"
             "        'Data Science and machine learning/Lecture08.ipynb',\n"
             "        'Data Science and machine learning/E03_geographicalspliting.ipynb']\n"
             "if cm is None:\n"
             "    print('Course material not configured (it is not distributed with this repository);'\n"
             "          ' set SUBSURFACEML_COURSE_DIR to check the cited files.')\n"
             "else:\n"
             "    for f in need:\n"
             "        print(f, '->', 'present' if (Path(cm) / f).exists() else 'NOT FOUND in ' + str(cm))"),
    ]


def nb02():
    return [
        md("# Supporting 2 - The simulator and its verification\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "Layered radial CO2-brine IMPES model (`impes.py`, from `3-IMPES.pdf`). "
           "This notebook (i) runs the two-layer case that exposed the old well "
           "coupling, (ii) reproduces the Buckley-Leverett benchmark, and (iii) "
           "reads the full verification report written by the pipeline."),
        code(SETUP + "\nfrom subsurfaceml.grid import RadialGrid, CartesianGrid1D\n"
             "from subsurfaceml.impes import TwoPhaseModel, InjectionSchedule\n"
             "from subsurfaceml.fluids import FluidProperties, RelPerm, RockProperties, bl_profile_1d, welge_shock\n"
             "from subsurfaceml.units import md_to_m2, MPA, YEAR, DAY"),
        md("## 1. One injector, two unequal layers, one bottom-hole pressure\n\n"
           "500 mD / porosity 0.25 against 20 mD / porosity 0.08 in a sealed "
           "compartment. The well equation `q_l = J_l (p_bh - p_l0)` with "
           "`sum q_l = Q` is solved together with the pressure field."),
        code("n = 30\ngrids = [RadialGrid(n=n, r_w=0.15, r_e=1500, h=10, r_near=5) for _ in range(2)]\n"
             "k = np.stack([np.full(n, md_to_m2(500)), np.full(n, md_to_m2(20))])\n"
             "phi = np.stack([np.full(n, .25), np.full(n, .08)])\n"
             "m = TwoPhaseModel(grids, k, phi, FluidProperties(), RelPerm(), RockProperties(), 15*MPA,\n"
             "                  outer_bc='closed', dt_max=30*DAY)\n"
             "t = np.linspace(0, 3*YEAR, 37)\n"
             "res = m.run(InjectionSchedule([0, 2*YEAR, 3*YEAR], [20.0, 0.0]), t)\n"
             "print('max spread of implied BHP between layers [Pa]:', res.diagnostics['max_bhp_spread_Pa'])\n"
             "print('max relative error of the total rate:', res.diagnostics['max_rate_rel_err'])\n"
             "print('CO2 mass-balance error:', res.mass_balance_error)\n"
             "fig, ax = plt.subplots(1, 2, figsize=(10, 3))\n"
             "ax[0].plot(t/YEAR, res.q_layer[:, 0]*m.fl.rho_g, label='500 mD layer')\n"
             "ax[0].plot(t/YEAR, res.q_layer[:, 1]*m.fl.rho_g, label='20 mD layer'); ax[0].legend()\n"
             "ax[0].set_xlabel('time [yr]'); ax[0].set_ylabel('layer rate [kg/s]')\n"
             "ax[1].plot(t/YEAR, (res.p_bh-15*MPA)/MPA, label='common BHP (diagnostic after shut-in)')\n"
             "ax[1].plot(t/YEAR, (res.p[:, 0, 0]-15*MPA)/MPA, '--', label='well block, layer 1')\n"
             "ax[1].plot(t/YEAR, (res.p[:, 1, 0]-15*MPA)/MPA, ':', label='well block, layer 2')\n"
             "ax[1].set_xlabel('time [yr]'); ax[1].set_ylabel('buildup [MPa]'); ax[1].legend(fontsize=7)"),
        md("The high-permeability layer takes most of the rate early; as its "
           "larger pore volume is pressurised the split drifts toward the pore-volume "
           "ratio, which is the sealed-compartment limit tested in "
           "`tests/test_well_coupling.py`. After shut-in each layer keeps its own "
           "pressure: no fluid crosses between layers through the closed well."),
        md("## 2. Buckley-Leverett (`4-CO2 BL.pdf` p.11-16)"),
        code("fl = FluidProperties(c_a=0, c_g=0); rp = RelPerm(); rk = RockProperties(c_r=0)\n"
             "L, A, ph, q = 100., 10., .2, 1e-5; T = .4*L*A*ph/q\n"
             "for nc in (100, 400):\n"
             "    g = CartesianGrid1D(n=nc, L=L, area=A)\n"
             "    mm = TwoPhaseModel([g], np.full((1, nc), md_to_m2(100)), np.full((1, nc), ph), fl, rp, rk,\n"
             "                       15*MPA, cfl=.3, max_dS=.05, dt_init=100., dt_max=T/50)\n"
             "    r = mm.run(InjectionSchedule([0, T], [q*fl.rho_g]), np.array([T]))\n"
             "    plt.plot(g.centres, r.Sg[-1, 0], label=f'IMPES {nc} cells')\n"
             "x = np.linspace(0, L, 2000)\n"
             "plt.plot(x, bl_profile_1d(rp, fl, x, T, q, A, ph, L=L), 'k--', label='Welge / MOC')\n"
             "plt.xlabel('x [m]'); plt.ylabel('S_g'); plt.legend()\n"
             "print('Welge shock saturation, fractional flow:', welge_shock(rp, fl)[:2])"),
        md("## 3. The verification report of the last pipeline run"),
        code("V = json.loads((Path(cfg.paths.metrics)/'validation.json').read_text())\n"
             "display(pd.Series(V['verdict']).to_frame('pass'))\n"
             "r7 = V['V6_V7_V8_radial_two_phase']\n"
             "for key in ('n_r', 'r_near', 'max_dS'):\n"
             "    print(key); display(pd.DataFrame(r7[key]).T[['dp_bh_max_MPa','r_plume_end_m','n_steps','wall_time_s']])\n"
             "c = r7['cfl']\n"
             "print('strict vs relaxed time stepping')\n"
             "display(pd.DataFrame({k: c[k] for k in ('relaxed', 'strict_default')}).T[\n"
             "    ['dp_bh_max_MPa', 'r_plume_end_m', 'mass_retained_Mt', 'n_steps', 'near_well_oscillation']])\n"
             "print('relative differences, strict vs relaxed:', {k: float(f'{v:.2g}') for k, v in c['rel_diff'].items()})\n"
             "print('time steps, strict / relaxed:', round(c['step_ratio_strict_over_relaxed'], 2))"),
        code("display(Image(str(Path(cfg.paths.figures)/'02_validation_convergence.png')))\n"
             "print(json.dumps(V['V10_upscaling_two_phase']['relative_error'], indent=1))"),
        md("## 4. V12 / V13: the two-phase bottom-hole pressure against the PSS solution\n\n"
           "Run in a single-phase-equivalent configuration (equal phase viscosities and "
           "compressibilities, linear relative permeabilities), the two-phase simulator must "
           "reproduce the pseudo-steady-state build-up of a bounded reservoir; the analytical "
           "ROM of `rom.py` is checked in the same limit."),
        code("display(pd.DataFrame(V['V12_V13_pss_well_pressure']).T[['sim_dp_bh_MPa', 'pss_analytic_dp_MPa',\n"
             "        'rel_err_sim_vs_pss', 'rom_dp_MPa', 'rel_err_rom_vs_pss']])"),
        md("V10 answers the question posed on `2-Upscaling.pdf` p.3-4: upscaling the "
           "layers into one (thickness-weighted arithmetic k, exact for single-phase "
           "parallel flow) keeps the pressure close but loses the layer-by-layer "
           "velocity contrast that controls the plume's leading edge."),
    ]


def nb03():
    return [
        md("# Supporting 3 - ML methods and studies in detail\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "Reads what `scripts/run_pipeline.py` wrote for the small demo configuration. Every split "
           "is grouped by reservoir realisation; the test reservoirs are fresh reservoirs generated "
           "with their own seed and used once, at the end."),
        code(SETUP + "\ndf = pd.read_csv(Path(cfg.paths.data)/'scenarios_features.csv')\n"
             "print(len(df), 'development scenarios,', df.realisation_id.nunique(), 'realisations')\n"
             "print('rows per role:', S['ml']['leakage']['rows'], '| overlaps:', S['ml']['leakage']['overlaps'])\n"
             "print(json.dumps(S['data_quality'], indent=1))"),
        md("## Model comparison (course families) and held-out errors in physical units"),
        code("rows = []\nfor t, r in S['ml']['targets'].items():\n"
             "    rows.append({'target': t, 'unit': r['unit'], 'selected': r['selected_model'],\n"
             "                 'test MAE': r['test']['MAE'], 'test RMSE': r['test']['RMSE'], 'test R2': r['test']['R2'],\n"
             "                 'max |error|': r['test']['max_abs_error'], 'mean-baseline RMSE': r['mean_baseline_test_rmse'],\n"
             "                 'interval case coverage': r['interval_test']['case_coverage'],\n"
             "                 'reservoirs fully covered': r['interval_test']['reservoir_all_covered'],\n"
             "                 'shift RMSE': r['shift']['RMSE']})\n"
             "display(pd.DataFrame(rows))\n"
             "print('grouped-CV RMSE of every family (training reservoirs; the only basis of selection):')\n"
             "display(pd.DataFrame({t: r['model_comparison_cv_rmse'] for t, r in S['ml']['targets'].items()}))"),
        code("display(Image(str(Path(cfg.paths.figures)/'06_surrogate_parity.png')))"),
        md("## Where the surrogates fail"),
        code("for t, r in S['ml']['targets'].items():\n"
             "    h = r['difficult_cases']\n"
             "    print(f\"\\n{t}: worst 10% of test cases carry {100*h['share_of_total_abs_error_from_worst_10pct']:.0f}% of the absolute error\")\n"
             "    display(pd.DataFrame(h['worst_cases']).round(3))\n"
             "    display(pd.DataFrame(h['by_permeability_tercile']))\n"
             "    display(pd.DataFrame(h['by_schedule_intensity_tercile']))"),
        md("## Pressure-limit screening"),
        code("b = S['classifier']['binary']\n"
             "display(pd.DataFrame(b['families']).T)\n"
             "print('imbalance handling (logistic, out-of-fold, threshold 0.5):')\n"
             "display(pd.DataFrame(b['imbalance_study_logistic_oof']).T)\n"
             "for k in ('test_default_threshold', 'test_selected_threshold', 'test_regression_surrogate_thresholded'):\n"
             "    print(k, {kk: v for kk, v in b[k].items()})\n"
             "print('interval upper edge as the screen:', b['test_regression_upper_bound'])\n"
             "tl = S['classifier']['traffic_light']\n"
             "display(pd.DataFrame(tl['families']).T); print('test:', tl['test'])\n"
             "display(Image(str(Path(cfg.paths.figures)/'10_classifier.png')))"),
        md("## Uncertainty: Monte Carlo over the assumed prior and error sources"),
        code("for t, r in S['uncertainty']['targets'].items():\n"
             "    print(t, {k: round(v, 4) for k, v in r['monte_carlo_prior'].items() if isinstance(v, float)})\n"
             "    e = r['error_sources']; print('   shares input/surrogate/numerical %:',\n"
             "          round(e['share_input_pct'], 1), round(e['share_surrogate_pct'], 1), round(e['share_numerical_pct'], 1))"),
        md("## ML-method studies (training reservoirs only)"),
        code("st = S['studies']\n"
             "for k in ('scaler_comparison', 'missing_descriptors', 'outliers', 'polynomial', 'column_transformer',\n"
             "          'split_comparison', 'ensembles', 'normal_equation'):\n"
             "    v = st[k]; print('\\n##', k)\n"
             "    print(json.dumps({a: b for a, b in v.items() if a != 'gd_cost_history_every_500'}, indent=1, default=str)[:1500])\n"
             "print(json.dumps({k: st['feature_selection'][k] for k in st['feature_selection']}, indent=1)[:2000])\n"
             "print(json.dumps({k: {kk: vv for kk, vv in v.items() if kk != 'best'} for k, v in st['tuning_strategies'].items()}, indent=1))\n"
             "display(Image(str(Path(cfg.paths.figures)/'14_ml_studies.png')))"),
        md("## Interpretation (model behaviour, not causality) and plume shapes"),
        code("I = S['interpretation']\n"
             "display(pd.DataFrame(I['dp_bh_max_MPa']['permutation_top8']))\n"
             "if 'shap' in I: display(pd.DataFrame(I['shap']['top'][:8]))\n"
             "print(json.dumps(I['local_case'], indent=1, default=str))\n"
             "print(json.dumps(I.get('plume_shapes', {}), indent=1)[:1500])\n"
             "display(Image(str(Path(cfg.paths.figures)/'13_plume_shapes.png')))"),
        md("## Cost"),
        code("print(json.dumps(S['speed'], indent=1))"),
    ]


def nb04():
    return [
        md("# Supporting 4 - Verification-gated screening on an independent reservoir\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "The surrogate proposes; the simulator decides. `screening.Recommendation` refuses to "
           "hold a schedule that has not been simulated and found within both stated limits. "
           "Limits are modelling assumptions."),
        code(SETUP + "\nfrom subsurfaceml.predict import Predictor\n"
             "from subsurfaceml import screening as SC\n"
             "from subsurfaceml.features import features_for_schedules\n"
             "from subsurfaceml.final_eval import eval_realisations\n"
             "from subsurfaceml.optimise import sample_candidates\n"
             "P = Predictor(cfg)   # verified artifacts; raises with a rebuild command if missing\n"
             "c, reals = eval_realisations(cfg, 'final_test')\n"
             "r = reals[0]\nprint(r)"),
        code("def predictor(R):\n"
             "    X = features_for_schedules(c, r, R)\n"
             "    _, p, hi = P.bands['dp_bh_max_MPa'].predict_interval(X)\n"
             "    _, p2, hi2 = P.bands['r_plume_m95_m'].predict_interval(X)\n"
             "    return {'dp': p, 'dp_hi': hi, 'r95': p2, 'r95_hi': hi2}\n"
             "X0 = features_for_schedules(c, r, np.ones((1, c.schedule.n_periods)))\n"
             "in_dom = bool(P.domain.check(X0)['in_domain'].iloc[0])\n"
             "cands = sample_candidates(c, r, 2000, np.random.default_rng(0))\n"
             "rec = SC.recommend_surrogate(c, r, SC.make_simulator(c, r), 4, predictor, cands, in_domain=in_dom)\n"
             "print('status:', rec.status, '| flags:', rec.flags)\n"
             "display(pd.DataFrame([ch.as_dict() for ch in rec.checks])[['label', 'rates_kg_s', 'dp_MPa', 'r95_m', 'mass_Mt', 'feasible']])\n"
             "provenance('computed', f'{rec.n_simulations} simulations run in this session')"),
        md("## What happens when nothing can be verified\n\n"
           "A limit no candidate can meet must give an explicit outcome and no recommendation."),
        code("import copy\nc2 = copy.deepcopy(c); c2.optim.p_limit_MPa = c2.solver.p_init_MPa + 0.05   # 0.05 MPa build-up\n"
             "rec2 = SC.recommend_surrogate(c2, r, SC.make_simulator(c2, r), 2, predictor, cands, fallback=None)\n"
             "print('status:', rec2.status, '| recommended:', rec2.recommended_rates_kg_s, '|', rec2.notes)"),
        md("## All screened reservoirs of the pipeline run"),
        code("rec_all = pd.read_csv(Path(cfg.paths.metrics)/'screening_recommendations.csv')\n"
             "display(rec_all[['realisation_id', 'set', 'method', 'status', 'mass_Mt', 'mass_vs_constant_pct',\n"
             "                 'n_simulations', 'flags']].round(3))\n"
             "display(Image(str(Path(cfg.paths.figures)/'15_schedule_screening.png')))\n"
             "provenance('loaded', 'screening results of the completed demo run')"),
    ]


def nb05():
    return [
        md("# Supporting 5 - Worked example: inputs -> simulation -> prediction -> evaluation\n\n*Optional detail; start with `notebooks/00_START_HERE.ipynb`.*\n\n"
           "Input file: `examples/worked_example_input.json` (assumed generic values, "
           "not a real site). The same steps are available from the command line:\n\n"
           "```\nsubsurfaceml simulate --config config/demo.yaml --input examples/worked_example_input.json\n"
           "subsurfaceml predict  --config config/demo.yaml --input examples/worked_example_input.json\n```"),
        code(SETUP + "\nfrom subsurfaceml.predict import Predictor, realisation_from_dict\n"
             "from subsurfaceml.scenarios import make_schedule, run_scenario, reference_rate\n"
             "from subsurfaceml.features import raw_inputs, features_for_schedules\n"
             "from subsurfaceml.units import MPA, YEAR\n"
             "case = json.loads((ROOT/'examples/worked_example_input.json').read_text())\n"
             "r = realisation_from_dict(case['reservoir']); rates = np.array(case['rates_kg_s'])\n"
             "print(r); print('rates [kg/s]:', rates)"),
        md("## Step 1 - inputs the surrogate sees (the single feature path)\n\n"
           "`raw_inputs` builds the layered rock with the realisation's seed, the "
           "closed-form reference rate and the end-point mobility ratio with this "
           "reservoir's own `krg0`; `engineer` adds log-transforms, flow capacity, "
           "pore volume and schedule-shape descriptors."),
        code("raw = raw_inputs(cfg, r, rates)\n"
             "print({k: raw[k] for k in ('V_DP_layers','q_ref_kg_s','endpoint_mobility_ratio','planned_mass_kg')})\n"
             "X = features_for_schedules(cfg, r, rates[None, :]); display(X.T.rename(columns={0: 'value'}))"),
        md("## Step 2 - simulate (the reference answer)"),
        code("o = run_scenario(cfg, r, make_schedule(cfg, r, rates), want_series=True)\n"
             "w, ts = o['row'], o['series']\n"
             "sim = {'dp_bh_max_MPa': w['dp_bh_max_Pa']/MPA, 'r_plume_m95_m': w['r_plume_m95_m'],\n"
             "       'sweep_efficiency': w['sweep_efficiency']}\n"
             "print(sim, '| wall time', round(w['wall_time_s'], 2), 's | mass balance', w['mass_balance_error'])\n"
             "fig, ax = plt.subplots(1, 2, figsize=(10, 3))\n"
             "ax[0].plot(ts.t_s/YEAR, ts.dp_bh_Pa/MPA); ax[0].axhline(cfg.optim.p_limit_MPa-cfg.solver.p_init_MPa, c='r', ls='--')\n"
             "ax[0].set_xlabel('Time [years]'); ax[0].set_ylabel('Bottom-hole pressure build-up [MPa]')\n"
             "ax[1].plot(ts.t_s/YEAR, ts.r_plume_m95_m); ax[1].set_xlabel('Time [years]'); ax[1].set_ylabel('Plume radius, 95 % of mass [m]')"),
        md("## Step 3 - predict with the saved surrogates"),
        code("P = Predictor(cfg)\nout = P.predict(r, rates[None, :])\n"
             "rows = []\nfor t in sim:\n"
             "    o_ = out[t]; p, lo, hi = o_['pred'][0], o_['band_low'][0], o_['band_high'][0]\n"
             "    rows.append({'quantity': t, 'simulated': sim[t], 'predicted': p, 'error': p - sim[t],\n"
             "                 'relative error %': 100*(p - sim[t])/sim[t], 'interval low': lo, 'interval high': hi,\n"
             "                 'inside interval': lo <= sim[t] <= hi, 'unit': o_['unit']})\n"
             "display(pd.DataFrame(rows))\n"
             "e = out['exceeds_pressure_limit']\n"
             "print('classifier flag (exceeds limit):', bool(e['flag'][0]), '| simulated exceedance:',\n"
             "      sim['dp_bh_max_MPa'] > e['dp_limit_MPa'])"),
        md("## Step 4 - evaluate: how does this case compare with the test-set error?"),
        code("for t in sim:\n"
             "    te = S['ml']['targets'][t]['test']\n"
             "    print(f\"{t}: this case |error| = {abs(out[t]['pred'][0]-sim[t]):.4g}; test MAE {te['MAE']:.4g}, \"\n"
             "          f\"max {te['max_abs_error']:.4g} {S['ml']['targets'][t]['unit']}\")\n"
             "print('in the training domain:', bool(out['in_training_domain'][0]))"),
        md("**Reading this result.** The table compares one simulated case with the "
           "surrogates' predictions and intervals. A prediction outside its interval is expected "
           "now and then -- for nominal 90 % intervals roughly one case in ten, and more often for "
           "a reservoir unlike the calibration reservoirs, which the domain flag reports. This is "
           "why the screening never relies on a prediction alone: any schedule that matters is "
           "simulated first."),
        md("## Step 5 - what-if: scale the whole schedule"),
        code("f = np.linspace(.4, 2, 33)\n"
             "pred = P.predict(r, np.outer(f, rates))['dp_bh_max_MPa']\n"
             "plt.plot(f, pred['pred']); plt.fill_between(f, pred['band_low'], pred['band_high'], alpha=.3)\n"
             "plt.axhline(cfg.optim.p_limit_MPa-cfg.solver.p_init_MPa, c='r', ls='--'); plt.axvline(1, c='grey')\n"
             "plt.xlabel('Whole schedule scaled by [-]'); plt.ylabel('Predicted peak build-up [MPa]')"),
    ]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--execute", action="store_true")
    a = ap.parse_args()
    SUP.mkdir(parents=True, exist_ok=True)
    books = {NB / "00_START_HERE.ipynb": nb00(),
             SUP / "s1_sources_and_coverage.ipynb": nb01(),
             SUP / "s2_simulator_verification.ipynb": nb02(),
             SUP / "s3_ml_methods_and_studies.ipynb": nb03(),
             SUP / "s4_schedule_screening.ipynb": nb04(),
             SUP / "s5_worked_example.ipynb": nb05()}
    for path, cells in books.items():
        nb = nbf.v4.new_notebook(cells=cells)
        nb.metadata["kernelspec"] = {"name": "python3", "display_name": "Python 3",
                                     "language": "python"}
        nbf.write(nb, path)
        print("wrote", path.relative_to(ROOT))
    if a.execute:
        from nbconvert.preprocessors import ExecutePreprocessor
        for path in books:
            nb = nbf.read(path, as_version=4)
            ExecutePreprocessor(timeout=1800, kernel_name="python3").preprocess(
                nb, {"metadata": {"path": str(path.parent)}})
            nbf.write(nb, path)
            print("executed", path.relative_to(ROOT))


if __name__ == "__main__":
    sys.exit(main())
