name: seisgeomech
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - matplotlib>=3.7
  - pytest>=7.4
  - jupyterlab>=4.0
  - pip
  - pip:
      - lasio>=0.31
      - bruges>=0.5.4
